/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClinicianRouteImport } from './routes/clinician'
import { Route as CareTeamRouteImport } from './routes/care-team'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicIotDoseRouteImport } from './routes/api.public.iot.dose'

const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicianRoute = ClinicianRouteImport.update({
  id: '/clinician',
  path: '/clinician',
  getParentRoute: () => rootRouteImport,
} as any)
const CareTeamRoute = CareTeamRouteImport.update({
  id: '/care-team',
  path: '/care-team',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIotDoseRoute = ApiPublicIotDoseRouteImport.update({
  id: '/api/public/iot/dose',
  path: '/api/public/iot/dose',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care-team': typeof CareTeamRoute
  '/clinician': typeof ClinicianRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/providers': typeof ProvidersRoute
  '/risk': typeof RiskRoute
  '/api/public/iot/dose': typeof ApiPublicIotDoseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care-team': typeof CareTeamRoute
  '/clinician': typeof ClinicianRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/providers': typeof ProvidersRoute
  '/risk': typeof RiskRoute
  '/api/public/iot/dose': typeof ApiPublicIotDoseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care-team': typeof CareTeamRoute
  '/clinician': typeof ClinicianRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/providers': typeof ProvidersRoute
  '/risk': typeof RiskRoute
  '/api/public/iot/dose': typeof ApiPublicIotDoseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care-team'
    | '/clinician'
    | '/dashboard'
    | '/devices'
    | '/join'
    | '/login'
    | '/medications'
    | '/providers'
    | '/risk'
    | '/api/public/iot/dose'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care-team'
    | '/clinician'
    | '/dashboard'
    | '/devices'
    | '/join'
    | '/login'
    | '/medications'
    | '/providers'
    | '/risk'
    | '/api/public/iot/dose'
  id:
    | '__root__'
    | '/'
    | '/care-team'
    | '/clinician'
    | '/dashboard'
    | '/devices'
    | '/join'
    | '/login'
    | '/medications'
    | '/providers'
    | '/risk'
    | '/api/public/iot/dose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareTeamRoute: typeof CareTeamRoute
  ClinicianRoute: typeof ClinicianRoute
  DashboardRoute: typeof DashboardRoute
  DevicesRoute: typeof DevicesRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MedicationsRoute: typeof MedicationsRoute
  ProvidersRoute: typeof ProvidersRoute
  RiskRoute: typeof RiskRoute
  ApiPublicIotDoseRoute: typeof ApiPublicIotDoseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician': {
      id: '/clinician'
      path: '/clinician'
      fullPath: '/clinician'
      preLoaderRoute: typeof ClinicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-team': {
      id: '/care-team'
      path: '/care-team'
      fullPath: '/care-team'
      preLoaderRoute: typeof CareTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iot/dose': {
      id: '/api/public/iot/dose'
      path: '/api/public/iot/dose'
      fullPath: '/api/public/iot/dose'
      preLoaderRoute: typeof ApiPublicIotDoseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareTeamRoute: CareTeamRoute,
  ClinicianRoute: ClinicianRoute,
  DashboardRoute: DashboardRoute,
  DevicesRoute: DevicesRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MedicationsRoute: MedicationsRoute,
  ProvidersRoute: ProvidersRoute,
  RiskRoute: RiskRoute,
  ApiPublicIotDoseRoute: ApiPublicIotDoseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
